#!/bin/sh

c00=$'\e[0;30m'
c01=$'\e[0;31m'
c02=$'\e[0;32m'
c03=$'\e[0;33m'
c04=$'\e[0;34m'
c05=$'\e[0;35m'
c06=$'\e[0;36m'
c07=$'\e[0;37m'
c08=$'\e[1;30m'
c09=$'\e[1;31m'
c10=$'\e[1;32m'
c11=$'\e[1;33m'
c12=$'\e[1;34m'
c13=$'\e[1;35m'
c14=$'\e[1;36m'
c15=$'\e[1;37m'

f0=$'\e[1;30m'
f1=$'\e[1;37m'
f2=$'\e[0;37m'

kernel=$(uname -rmo)
cpuspe=$(grep 'model name' /proc/cpuinfo| sed 1q|sed 's/^.*:\ *//')

system=$(cat /etc/os-release | sed '2,$d;s/NAME="//;s/"//')

if [ -n "$DISPLAY" ]; then
    wmname=$(xprop -root _NET_WM_NAME|cut -d\" -f2)
    termfn=$(cat $HOME/.Xresources | grep -v ! | awk '/*font/ {print $2}' | sed 's/xft://;s/:pixelsize//;s/=/\ /')
else
    wmname="none"
    termfn="none"
fi
wmname="2bwm"

pkgnum=$(pacman -Q|wc -l)
birthd=$(sed -n '1s/^\[\([0-9-]*\).*$/\1/p' /var/log/pacman.log | tr - .)

gitdir="github.com/xerolution"
myblog="zerolution.deviantart.com"

cat << EOF
${c01}
▉▉▉▉▉  ▉▉▉▉  ▉▉▉▉  ▉▉▉▉  ▉     ▉  ▉  ▉▉▉▉▉  ▉  ▉▉▉▉  ▉▉  ▉
   ▉   ▉     ▉  ▉  ▉  ▉  ▉     ▉  ▉    ▉    ▉  ▉  ▉  ▉ ▉ ▉
  ▉    ▉▉▉▉  ▉▉▉▉  ▉  ▉  ▉     ▉  ▉    ▉    ▉  ▉  ▉  ▉ ▉ ▉
 ▉     ▉     ▉ ▉   ▉  ▉  ▉     ▉  ▉    ▉    ▉  ▉  ▉  ▉  ▉▉
▉▉▉▉▉  ▉▉▉▉  ▉  ▉  ▉▉▉▉  ▉▉▉▉  ▉▉▉▉    ▉    ▉  ▉▉▉▉  ▉   ▉

${c01}OS ${f0}........... $f2$system
${c01}name ${f0}......... $f2$HOSTNAME
${c01}birth day${f0}..... $f2$birthd
${c01}packages ${f0}..... $f2$pkgnum

${c01}wm ${f0}........... $f2$wmname
${c01}shell ${f0}........ $f2$SHELL
${c01}terminal ${f0}..... $f2$TERM
${c01}term font ${f0}.... $f2$termfn

${c01}kernel ${f0}....... $f2$kernel
${c01}processor ${f0}.... $f2$cpuspe

${c01}website ${f0}...... $f2$myblog
${c01}github ${f0}....... $f2$gitdir
 
${c00}black${c01} red${c02} green${c03} yellow${c04} blue${c05} magenta${c06} cyan${c07} white
${c08}black${c09} red${c10} green${c11} yellow${c12} blue${c13} magenta${c14} cyan${c15} white
EOF
